// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHJ0a7Rzl8g6kl0-fdCgstVd0IRIq3_3',
    appId: '1:175983858000:web:1de008ba137f65e679dc55',
    messagingSenderId: '175983858000',
    projectId: 'shopfi-28674',
    authDomain: 'shopfi-28674.firebaseapp.com',
    storageBucket: 'shopfi-28674.appspot.com',
    measurementId: 'G-7FW902ZNCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVfCIOeEYZJzA4dZQ1iNFn19pNZ8CYwR',
    appId: '1:175983858000:android:62076df8f188f5bf79dc55',
    messagingSenderId: '175983858000',
    projectId: 'shopfi-28674',
    storageBucket: 'shopfi-28674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpFOxOCk1OFMNySQwKiZNFHpHtvuKFp-',
    appId: '1:175983858000:ios:f9670bf9c146320b79dc55',
    messagingSenderId: '175983858000',
    projectId: 'shopfi-28674',
    storageBucket: 'shopfi-28674.appspot.com',
    iosClientId: '175983858000-j5tdmuf94c3nfmebochen54u1t2beoom.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopfi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpFOxOCk1OFMNySQwKiZNFHpHtvuKFp-',
    appId: '1:175983858000:ios:9252bd8e5f6111c279dc55',
    messagingSenderId: '175983858000',
    projectId: 'shopfi-28674',
    storageBucket: 'shopfi-28674.appspot.com',
    iosClientId: '175983858000-e8aroaeg9gpr6tjco05383k102u2q7os.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopfi.RunnerTests',
  );
}
